version: "3.4"

services:
  proxy:
    image: caddy:latest
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - backend
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./.caddy/data:/data
      - ./.caddy/config:/config
    environment:
      - DOMAIN=phisherman.example.com
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: unless-stopped
    volumes:
      - ./access.log:/app/access.log
      - ./config.json:/app/config.json
